import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';

test('PostgreSQL migration + RLS + atomic publication + leads + rate limit',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create schema storage;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth,storage to anon,authenticated,service_role;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;grant all on storage.objects to anon,authenticated,service_role;`);
 await db.exec(await readFile('supabase/migrations/001_initial.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/002_image_order.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/004_increase_property_image_limit.sql','utf8'));
 assert.equal((await db.query<{file_size_limit:number}>("select file_size_limit from storage.buckets where id='property-images'")).rows[0].file_size_limit,52428800);
 const admin='00000000-0000-4000-8000-000000000001',normal='00000000-0000-4000-8000-000000000002';
 await db.exec(`insert into auth.users values('${admin}'),('${normal}');insert into public.admin_profiles(id,display_name) values('${admin}','Admin');`);
 await db.exec(`set role authenticated;set request.jwt.claim.sub='${admin}'`);
 const draft={property_name:'Test House',slug:'test-house',property_code:'TEST-1',prefecture:'osaka',city:'箕面市',rent:180000,status:'draft',featured:false};
 const s={advertising_permission:false};
 const created=await db.query<{save_property:string}>('select public.save_property(null,$1::jsonb,$2::jsonb)',[JSON.stringify(draft),JSON.stringify(s)]);
 const id=created.rows[0].save_property;
 assert.ok(id);
 await assert.rejects(()=>db.query('select public.save_property($1,$2::jsonb,$3::jsonb)',[id,JSON.stringify({...draft,status:'published'}),JSON.stringify(s)]),/PUBLICATION_PERMISSION_REQUIRED/);
 assert.equal((await db.query<{status:string}>('select status from properties where id=$1',[id])).rows[0].status,'draft');
 await db.query("insert into property_images(property_id,storage_path) values($1,$2)",[id,`${id}/test.jpg`]);
 await db.query("insert into storage.objects(bucket_id,name) values('property-images',$1)",[`${id}/test.jpg`]);
 const source={advertising_permission:true,permission_confirmed_at:'2026-01-01',internal_notes:'PRIVATE NOTE'};
 await db.query('select public.save_property($1,$2::jsonb,$3::jsonb)',[id,JSON.stringify({...draft,status:'published',transaction_type:'仲介',information_checked_at:'2026-01-01',next_update_at:'2099-01-01'}),JSON.stringify(source)]);
 const second=await db.query<{save_property:string}>('select public.save_property(null,$1::jsonb,$2::jsonb)',[JSON.stringify({...draft,slug:'draft-house',property_code:'TEST-2'}),JSON.stringify(s)]);
 const draftId=second.rows[0].save_property;
 await db.query("insert into property_images(property_id,storage_path) values($1,$2)",[draftId,`${draftId}/private.jpg`]);
 await db.query("insert into storage.objects(bucket_id,name) values('property-images',$1)",[`${draftId}/private.jpg`]);
 await db.exec('reset role;set role anon;set request.jwt.claim.sub=\'\'');
 assert.equal((await db.query('select * from properties')).rows.length,1);
 assert.equal((await db.query('select * from property_images')).rows.length,1);
 assert.equal((await db.query('select * from storage.objects')).rows.length,1);
 for(const table of ['property_sources','admin_profiles','inquiries','property_requests'])await assert.rejects(()=>db.query(`select * from ${table}`),/permission denied/);
 await assert.rejects(()=>db.query("select public.consume_rate_limit('x',5)"),/permission denied/);
 await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${normal}'`);
 assert.equal((await db.query('select * from properties')).rows.length,1);
 assert.equal((await db.query('select * from property_sources')).rows.length,0);
 assert.equal((await db.query('select * from admin_profiles')).rows.length,0);
 await assert.rejects(()=>db.query(`insert into admin_profiles(id,display_name) values('${normal}','hacker')`),/permission denied/);
 await assert.rejects(()=>db.query('select public.save_property(null,$1::jsonb,$2::jsonb)',[JSON.stringify(draft),JSON.stringify(s)]),/FORBIDDEN/);
 await db.exec(`reset role;set role service_role`);
 for(let i=0;i<5;i++)assert.equal((await db.query<{consume_rate_limit:boolean}>("select consume_rate_limit('hashed-test',5)")).rows[0].consume_rate_limit,true);
 assert.equal((await db.query<{consume_rate_limit:boolean}>("select consume_rate_limit('hashed-test',5)")).rows[0].consume_rate_limit,false);
 await db.query("insert into inquiries(submission_id,property_id,property_name_snapshot,name,email,inquiry_type,message,source_url) values(gen_random_uuid(),$1,'Test House','Customer','test@example.com','内見したい','Test','https://example.com')",[id]);
 await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${normal}'`);
 assert.equal((await db.query('select * from inquiries')).rows.length,0);
 await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${admin}'`);
 assert.equal((await db.query('select * from inquiries')).rows.length,1);
 await db.exec("update inquiries set status='viewing',internal_notes='appointment'");
 assert.equal((await db.query<{status:string}>('select status from inquiries')).rows[0].status,'viewing');
 await db.query('update property_sources set advertising_permission=false where property_id=$1',[id]);
 assert.equal((await db.query<{status:string}>('select status from properties where id=$1',[id])).rows[0].status,'draft');
 await db.close();
});
