import Link from 'next/link';
import {Menu,CarFront} from 'lucide-react';
import {demoMode,configured} from '@/lib/config';
export function Header(){return <><a className="skip-link" href="#main">本文へ移動</a>{demoMode()&&<div className="preview-banner">PREVIEW — 掲載物件・条件は架空のサンプルです。お問い合わせは送信されません。</div>}<header className="site-header"><Link className="wordmark" href="/">GARAGE HOUSE<span>NAVI<span className="brand-line"/></span></Link><nav className="desktop-nav" aria-label="メインナビゲーション"><Link href="/properties">物件を探す</Link><Link href="/areas">エリアから探す</Link><Link href="/properties#garage-filters">ガレージ条件</Link><Link href="/journal">GARAGE LIFE</Link></nav><Link className="header-cta" href="/request">希望条件から探してもらう</Link><details className="mobile-menu"><summary aria-label="メニュー"><Menu size={25}/></summary><nav aria-label="モバイルナビゲーション"><Link href="/properties">物件を探す</Link><Link href="/areas">エリアから探す</Link><Link href="/properties#garage-filters">ガレージ条件から探す</Link><Link href="/journal">GARAGE LIFE</Link><Link href="/request">物件リクエスト</Link></nav></details></header></>}
export function Footer(){return <footer className="footer"><div className="footer-top"><Link className="wordmark" href="/">GARAGE HOUSE<span>NAVI<span className="brand-line"/></span></Link><p>愛車と暮らす、理想の住まいを。</p></div><div className="footer-links"><Link href="/properties">物件を探す</Link><Link href="/areas">エリアから探す</Link><Link href="/properties#garage-filters">ガレージ条件</Link><Link href="/journal">GARAGE LIFE</Link><Link href="/request">物件リクエスト</Link></div><div className="footer-bottom"><small>© {new Date().getFullYear()} GARAGE HOUSE NAVI</small><nav aria-label="運営情報"><Link href="/company">運営会社</Link><Link href="/contact">お問い合わせ</Link><Link href="/terms">利用規約</Link><Link href="/privacy">プライバシーポリシー</Link></nav></div></footer>}
export function MobileNav(){return <nav className="mobile-bottom" aria-label="クイックアクセス"><Link href="/properties"><CarFront size={18}/>物件検索</Link><Link href="/request">希望条件を送る</Link></nav>}
export function RequestCTA(){return <section className="request-cta"><div><p className="eyebrow">YOUR NEXT GARAGE</p><h2>探している物件が<br className="mobile-only"/>見つからない？</h2><p>Web未掲載物件を含め、ご希望条件に合う<br/>ガレージハウス探しをお手伝いします。</p></div><Link className="button light" href="/request">希望条件を送る</Link></section>}
export function SetupNotice(){return !configured()&&!demoMode()?<div className="notice">現在、掲載準備中です。公開物件の登録後、このページに表示されます。</div>:null}
export function Breadcrumb({items}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumbs" aria-label="パンくず"><Link href="/">HOME</Link>{items.map((item,i)=><span key={i}><span aria-hidden="true">/</span>{item.href?<Link href={item.href}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}</span>)}</nav>}
