export const PREFECTURES = [{"slug": "hokkaido", "name": "北海道", "code": "01"}, {"slug": "aomori", "name": "青森県", "code": "02"}, {"slug": "iwate", "name": "岩手県", "code": "03"}, {"slug": "miyagi", "name": "宮城県", "code": "04"}, {"slug": "akita", "name": "秋田県", "code": "05"}, {"slug": "yamagata", "name": "山形県", "code": "06"}, {"slug": "fukushima", "name": "福島県", "code": "07"}, {"slug": "ibaraki", "name": "茨城県", "code": "08"}, {"slug": "tochigi", "name": "栃木県", "code": "09"}, {"slug": "gunma", "name": "群馬県", "code": "10"}, {"slug": "saitama", "name": "埼玉県", "code": "11"}, {"slug": "chiba", "name": "千葉県", "code": "12"}, {"slug": "tokyo", "name": "東京都", "code": "13"}, {"slug": "kanagawa", "name": "神奈川県", "code": "14"}, {"slug": "niigata", "name": "新潟県", "code": "15"}, {"slug": "toyama", "name": "富山県", "code": "16"}, {"slug": "ishikawa", "name": "石川県", "code": "17"}, {"slug": "fukui", "name": "福井県", "code": "18"}, {"slug": "yamanashi", "name": "山梨県", "code": "19"}, {"slug": "nagano", "name": "長野県", "code": "20"}, {"slug": "gifu", "name": "岐阜県", "code": "21"}, {"slug": "shizuoka", "name": "静岡県", "code": "22"}, {"slug": "aichi", "name": "愛知県", "code": "23"}, {"slug": "mie", "name": "三重県", "code": "24"}, {"slug": "shiga", "name": "滋賀県", "code": "25"}, {"slug": "kyoto", "name": "京都府", "code": "26"}, {"slug": "osaka", "name": "大阪府", "code": "27"}, {"slug": "hyogo", "name": "兵庫県", "code": "28"}, {"slug": "nara", "name": "奈良県", "code": "29"}, {"slug": "wakayama", "name": "和歌山県", "code": "30"}, {"slug": "tottori", "name": "鳥取県", "code": "31"}, {"slug": "shimane", "name": "島根県", "code": "32"}, {"slug": "okayama", "name": "岡山県", "code": "33"}, {"slug": "hiroshima", "name": "広島県", "code": "34"}, {"slug": "yamaguchi", "name": "山口県", "code": "35"}, {"slug": "tokushima", "name": "徳島県", "code": "36"}, {"slug": "kagawa", "name": "香川県", "code": "37"}, {"slug": "ehime", "name": "愛媛県", "code": "38"}, {"slug": "kochi", "name": "高知県", "code": "39"}, {"slug": "fukuoka", "name": "福岡県", "code": "40"}, {"slug": "saga", "name": "佐賀県", "code": "41"}, {"slug": "nagasaki", "name": "長崎県", "code": "42"}, {"slug": "kumamoto", "name": "熊本県", "code": "43"}, {"slug": "oita", "name": "大分県", "code": "44"}, {"slug": "miyazaki", "name": "宮崎県", "code": "45"}, {"slug": "kagoshima", "name": "鹿児島県", "code": "46"}, {"slug": "okinawa", "name": "沖縄県", "code": "47"}] as const;
export const KANSAI = ['osaka','hyogo','kyoto','nara'];
export const prefectureName = (slug: string) => PREFECTURES.find(p => p.slug === slug)?.name ?? slug;
export const FEATURES = [
 ['shutter','シャッター'],['electric_shutter','電動シャッター'],['ev_charger','EV充電'],
 ['motorcycle','バイク可'],['large_vehicle','大型車対応'],['direct_access','室内直結'],
 ['pet','ペット可'],['diy','DIY可'],['soho','SOHO可'],['office_use','事務所利用可']
] as const;
export const LEAD_STATUSES = {new:'新規',contacted:'連絡済',viewing:'内見予定',application:'申込',closed_won:'成約',closed_lost:'見送り'} as const;
export const PROPERTY_STATUSES = {draft:'下書き',published:'公開中',closed:'募集終了'} as const;
export const INQUIRY_TYPES = ['空室状況を確認したい','内見したい','初期費用を知りたい','その他'] as const;
export const LAYOUTS = ['1R','1K','1DK','1LDK','2K','2DK','2LDK','3LDK','4LDK以上','その他'];
export const money = (n: number | null | undefined) => n == null ? '確認中' : `${n.toLocaleString('ja-JP')}円`;
export const rentLabel = (n: number) => (n/10000).toLocaleString('ja-JP',{maximumFractionDigits:2});
export const mm = (n: number | null | undefined) => n == null ? '確認中' : `${n.toLocaleString('ja-JP')} mm`;
