import {NextResponse} from 'next/server';import {z} from 'zod';import {getAdmin} from '@/lib/supabase';import {sameOrigin,readJson} from '@/lib/security';
export async function POST(request:Request){if(!sameOrigin(request))return NextResponse.json({error:'不正なリクエストです。'},{status:403});const admin=await getAdmin();if(!admin)return NextResponse.json({error:'ログインが必要です。'},{status:401});try{if(Number(request.headers.get('content-length'))>11*1024*1024)return NextResponse.json({error:'ファイルが大きすぎます。'},{status:413});const data=await request.formData();const id=z.uuid().parse(data.get('property_id'));const file=data.get('file');const types:Record<string,string>={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/avif':'avif'};if(!(file instanceof File)||!types[file.type]||file.size>10*1024*1024||file.size===0)return NextResponse.json({error:'JPEG / PNG / WebP / AVIF、10MB以内の写真を選んでください。'},{status:422});
 const bytes=new Uint8Array(await file.arrayBuffer());const jpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71;const webp=Buffer.from(bytes.slice(0,4)).toString()==='RIFF'&&Buffer.from(bytes.slice(8,12)).toString()==='WEBP';const avif=Buffer.from(bytes.slice(4,8)).toString()==='ftyp'&&/avif|avis/.test(Buffer.from(bytes.slice(8,32)).toString());if(!({'image/jpeg':jpeg,'image/png':png,'image/webp':webp,'image/avif':avif}[file.type]))return NextResponse.json({error:'画像ファイルの形式を確認してください。'},{status:422});
 const {data:property}=await admin.db.from('properties').select('id,property_name').eq('id',id).maybeSingle();if(!property)return NextResponse.json({error:'物件が見つかりません。'},{status:404});const {data:existing,error:readError}=await admin.db.from('property_images').select('sort_order').eq('property_id',id).order('sort_order',{ascending:false});if(readError)throw readError;if((existing?.length??0)>=30)return NextResponse.json({error:'写真は30枚までです。'},{status:422});const path=`${id}/${crypto.randomUUID()}.${types[file.type]}`;const {error:uploadError}=await admin.db.storage.from('property-images').upload(path,bytes,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {data:image,error}=await admin.db.from('property_images').insert({property_id:id,storage_path:path,alt:property.property_name,sort_order:(existing?.[0]?.sort_order??-1)+1}).select().single();if(error){await admin.db.storage.from('property-images').remove([path]);throw error;}const {data:signed}=await admin.db.storage.from('property-images').createSignedUrl(path,3600);return NextResponse.json({image:{...image,url:signed?.signedUrl}});
 }catch{return NextResponse.json({error:'アップロードできませんでした。接続とファイルを確認してください。'},{status:500});}}
export async function PATCH(request:Request){if(!sameOrigin(request))return NextResponse.json({error:'不正なリクエストです。'},{status:403});const admin=await getAdmin();if(!admin)return NextResponse.json({error:'ログインが必要です。'},{status:401});try{const schema=z.object({property_id:z.uuid(),id:z.uuid(),action:z.enum(['delete','reorder','alt']),order:z.array(z.uuid()).max(30).optional(),alt:z.string().max(300).optional()});const body=schema.parse(await readJson(request));const {data:images,error}=await admin.db.from('property_images').select('*').eq('property_id',body.property_id);if(error)throw error;const img=images?.find(x=>x.id===body.id);if(!img)return NextResponse.json({error:'画像が見つかりません。'},{status:404});if(body.action==='delete'){const {data:p}=await admin.db.from('properties').select('status').eq('id',body.property_id).single();if(p?.status==='published'&&images?.length===1)return NextResponse.json({error:'公開中の最後の写真は削除できません。先に下書きへ変更してください。'},{status:422});const {error:del}=await admin.db.from('property_images').delete().eq('id',img.id);if(del)throw del;await admin.db.storage.from('property-images').remove([img.storage_path]);}
 else if(body.action==='alt'){const {error:e}=await admin.db.from('property_images').update({alt:body.alt||''}).eq('id',img.id);if(e)throw e;}
 else {const order=body.order||[];if(order.length!==images?.length||new Set(order).size!==order.length||!order.every(id=>images.some(x=>x.id===id)))return NextResponse.json({error:'画像一覧が変更されました。再読み込みしてください。'},{status:409});const {error:e}=await admin.db.rpc('reorder_property_images',{p_property_id:body.property_id,p_ids:order});if(e)throw e;}
 return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'画像を更新できませんでした。'},{status:400});}}
