import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base,{waitUntil:'load'});await page.locator('h1').waitFor();
assert.equal((await page.title()).includes('GARAGE HOUSE NAVI'),true,'Application did not load');
await page.screenshot({path:'../preview-desktop.png',fullPage:true});
assert.equal(await page.locator('.property-card').count(),6);
await page.goto(`${base}/properties?prefecture=osaka&garage_count=2`);
assert.equal(await page.locator('.property-card').count(),1);
await page.getByRole('link',{name:'MINOH GARAGE RESIDENCE',exact:true}).click();
await page.getByRole('heading',{name:'GARAGE SPEC',exact:true}).waitFor();
assert.ok((await page.locator('title').textContent()).includes('MINOH'));
assert.equal(await page.getByRole('button',{name:'お問い合わせを送信する'}).isDisabled(),true);
await page.goto(`${base}/properties?garage_width_mm=99999`);
await page.getByText('条件に合う物件が見つかりませんでした。',{exact:true}).waitFor();
await page.locator('.empty-state').getByRole('link',{name:'希望条件を送る',exact:true}).click();
assert.ok((await page.locator('[name=must_haves]').inputValue()).includes('99999'));
await page.goto(`${base}/admin`);assert.ok(page.url().includes('/login'));
await page.setViewportSize({width:390,height:844});
await page.goto(base);await page.screenshot({path:'../preview-mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);assert.equal(overflow,false);
await page.locator('.mobile-menu summary').click();await page.locator('.mobile-menu nav').getByRole('link',{name:'物件を探す',exact:true}).click();
assert.ok(page.url().includes('/properties'));
for(const route of ['/request','/osaka','/osaka/minoh','/areas','/privacy','/properties/sample-minoh-residence']){await page.goto(base+route);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route);}
await page.goto(`${base}/properties/sample-minoh-residence`);await page.screenshot({path:'../preview-detail-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);
await browser.close();
console.log('PASS: desktop/mobile rendering, search, detail metadata, zero-state condition handoff, disabled unconnected forms, admin redirect, mobile navigation and no overflow.');
